# Copyright (c) Meta Platforms, Inc. and affiliates. All Rights Reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

from torch import Generator, Tensor

def supports_cuda() -> bool: ...
def encrypt(input: Tensor, output: Tensor, key: Tensor, cipher, mode): ...
def decrypt(input: Tensor, output: Tensor, key: Tensor, cipher, mode): ...
def __version__() -> str: ...
def git_version() -> str: ...
def create_generator_(key: Tensor) -> Generator: ...
